from dotenv import load_dotenv

import os

from langchain.agents import create_agent
from langchain.tools import tool
from langchain_core.messages import HumanMessage
from langchain_ollama import ChatOllama

from typing import List
from pydantic import BaseModel, Field   

load_dotenv()

class Source(BaseModel):
    """Schema for a source used by agent."""
    url: str = Field(description="The URL of the source.")
    
class AgentResponse(BaseModel):
    """Schema for the response from the agent."""
    answers: str = Field(description="The answer generated by the agent.")
    sources: List[Source] = Field(default_factory = list, description="A list of sources used by the agent to generate the answer.")
    
@tool
def search(query: str) -> str:
    """_summary_

    Args:
        query (str): _description_

    Returns:
        str: _description_
    """

    print(f"Searching for: {query}")
    return f"Results for: {query}"

llm = ChatOllama(
    model="qwen2.5:1.5b",
    base_url=os.environ.get("OLLAMA_BASE_URL"),
    temperature=0,
)

tools = [search]

agent = create_agent(
    model=llm,
    tools=tools,
    response_format = AgentResponse
)

def main():
    result = agent.invoke(
        {"messages": HumanMessage(content="Search 3 jobs postings for a AI Engineer in Vietnam on the Linkedin and list their URL and the company name.")},
    )
    print(result)
    
if __name__ == "__main__":
    main()